<?php

$apiKey = "";
include 'connect.php';
session_start();
$amt=$_SESSION['final'];
$famt=$amt*100;
?>
<form action="bookcheck.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey ; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount=<?php echo $famt; ?> // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Transit-Ease"
    data-description="Train Ticket Booking"
    data-image="https://i.ibb.co/j5n88kR/logo.png"
    data-prefill.name=""
    data-prefill.email=""
    data-theme.color="#283c63"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>

